# Generated by Django 4.2.6 on 2023-12-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0002_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='User',
            new_name='user',
        ),
    ]
