# Generated by Django 4.2.6 on 2023-12-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0003_rename_user_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Complete',
            new_name='complete',
        ),
    ]
