# Generated by Django 4.2.6 on 2023-12-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_App', '0004_rename_complete_task_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='Complete',
        ),
    ]
